import { z } from 'zod';
const productSchema = z.object({
  id: z.string().uuid().optional(),
  slug: z.string().min(2).max(120),
  name: z.string().min(1).max(200),
  tagline: z.string().max(300).nullable().optional(),
  description: z.string().max(4000).nullable().optional(),
  category: z.string().max(60).nullable().optional(),
  flora: z.string().max(60).nullable().optional(),
  badge: z.string().max(40).nullable().optional(),
  price: z.number().int().nonnegative(),
  price_max: z.number().int().nonnegative().nullable().optional(),
  mrp: z.number().int().nonnegative().nullable().optional(),
  rating: z.number().min(0).max(5).optional(),
  reviews_count: z.number().int().nonnegative().optional(),
  sizes: z.array(z.string()).default([]),
  benefits: z.array(z.string()).default([]),
  image_key: z.string().max(120).nullable().optional(),
  image_url: z.string().max(2000).nullable().optional(),
  stock_quantity: z.number().int().nonnegative().default(100),
  in_stock: z.boolean().default(true),
  published: z.boolean().default(true),
  sort_order: z.number().int().default(0),
  sku: z.string().max(80).nullable().optional(),
  barcode: z.string().max(80).nullable().optional(),
  brand: z.string().max(80).nullable().optional(),
  ingredients: z.string().max(4000).nullable().optional(),
  usage_instructions: z.string().max(4000).nullable().optional(),
  warnings: z.string().max(2000).nullable().optional(),
  cost_price_paise: z.number().int().nonnegative().nullable().optional(),
  gst_percent: z.number().min(0).max(50).nullable().optional(),
  hsn_code: z.string().max(40).nullable().optional(),
  weight_g: z.number().int().nonnegative().nullable().optional(),
  low_stock_limit: z.number().int().nonnegative().default(5),
  status: z.enum(["draft","published","archived"]).default("published"),
  is_featured: z.boolean().default(false),
  is_bestseller: z.boolean().default(false),
  is_new_arrival: z.boolean().default(false),
  show_on_homepage: z.boolean().default(false),
  images: z.array(z.string().max(2000)).default([]),
  additional_images: z.array(z.string().max(2000)).default([]).optional(),
  video_url: z.string().max(2000).nullable().optional(),
  meta_title: z.string().max(200).nullable().optional(),
  meta_description: z.string().max(400).nullable().optional(),
  meta_keywords: z.string().max(400).nullable().optional(),
  canonical_url: z.string().max(2000).nullable().optional(),
  attributes: z.record(z.string(), z.any()).optional(),
});

const payload = {
  id: "eecfa722-e1d5-4521-af9c-097a8a1c97a2",
  slug: "ajwain-honey",
  name: "Ajwain Honey",
  tagline: "Raw • Unfiltered • Unheated",
  description: "Sourced from the nectar of Ajwain flowers...",
  category: "Honey",
  flora: null,
  badge: "Bestseller",
  price: 349,
  price_max: null,
  mrp: null,
  rating: 4.8,
  reviews_count: 0,
  sizes: ["250g"],
  benefits: ["Supports digestion"],
  image_key: "prod-ajwain",
  image_url: null,
  images: ["prod-ajwain", "prod-liquid", "bee-farm", "team-beekeepers"],
  additional_images: ["https://..."],
  stock_quantity: 0,
  in_stock: false,
  published: true,
  sort_order: 0,
  sku: null,
  barcode: null,
  brand: null,
  ingredients: null,
  usage_instructions: null,
  warnings: null,
  cost_price_paise: null,
  gst_percent: null,
  hsn_code: null,
  weight_g: null,
  low_stock_limit: 5,
  status: "published",
  is_featured: false,
  is_bestseller: false,
  is_new_arrival: false,
  show_on_homepage: false,
  video_url: null,
  meta_title: null,
  meta_description: null,
  meta_keywords: null,
  canonical_url: null,
  attributes: {},
};

try {
  productSchema.parse(payload);
  console.log("PASS");
} catch(e: any) {
  console.log("FAIL", JSON.stringify(e.errors, null, 2));
}
